### ISSUE TITLE
Browser Login UI Slides along on the window on initial display, 

### ISSUE THREAD

**Issue by mrrobdlon** [passbolt/passbolt_browser_extension#171]
## Browser Login UI Slides along on the window on initial display, sometimes ends up in unusable positions

* Passbolt Version: 3.11.1 (Extension Version)
* Platform and Target:
-- Browser: Version 110.0.5481.178 (Official Build) (64-bit)
-- Windows 11 Home 22621.1265

### What you did
Navigate to any login page while not logged into PassBolt
Click the PassBolt icon in Chrome Extensions QuickAccess
Chase the popup around trying to click in it and type it into get frustrated, wait for it to stop, finish logging in

### What happened
The UI (pop-over?) appears and then moves from right to left for about 5 seconds.
This is intermittent, happens about 70% of the time, even for the same website it can happen sometimes and other times not

### What you expected to happen
The UI popup should not move after it appears and I can click on it, give it focus and enter my PassBolt login details so that I can login to whatever other site I'm working with.

I use PassBolt all day every day so this may seem trivial but I'm hitting it 15+ times per day

**Comment by Benj1er** [comment]
Hello @mrrobdlon,

We will investigate on this issue.

Could you give us more details on the steps to reproduce this issue?
Do you click on the passbolt icon in a login form or directly on the extension icon in the toolbar?

Thank you in advance for your help

**Comment by mrrobdlon** [comment]
Hi @Benj1er 

Thanks for looking into it.

I've been paying closer attention to the behaviour today and I misreported the issue. It happens quite consistently when clicking the icon in a login form, and doesn't seem to happen when clicking the toolbar / Chrome Extensions QuickAccess

The environment is:

Passbolt Version: 3.11.1 (Extension Version)
Platform and Target:
-- Browser: Chrome Version 110.0.5481.178 (Official Build) (64-bit)
-- Windows 11 Home 22621.1265

I'll update the original issue

**Comment by Benj1er** [comment]
Hello @mrrobdlon,

Does the issue persist in the latest version released (v4.1.0)?
Do you have an application that manages window positioning?

Thank you in advance for your help

**Comment by mrrobdlon** [comment]
Hi - Sorry for the delayed response, the notification went to a lesser used email address. Thanks for looking into this.

I don't have any browser extensions or windows apps installed that manage that type of thing. Only the default Windows 11 "Window Snap" feature.

I'm still seeing the behaviour, for example on https://login.salesforce.com/

Here's a video, please excuse the editing, I needed to blur out confidential information.
https://drive.google.com/file/d/1JPoeE5KMokcnq1GNCAUAeHLxMTuA0Rbj/view?usp=sharing

**Comment by Benj1er** [comment]
Hi @mrrobdlon,

Thank you for your feedback, the video will help us to have a better understanding of the issue.
We will be investigating further to resolve the issue and let you know when a fix is available.

A follow-up ticket was created on the internal tracker: PB-25511

Best regards

**Comment by scadra** [comment]
Hi @mrrobdlon,

We have tried to reproduce your issue this morning, without success unfortunately.
We saw during the investigation that you have extensions installed, 4 are pins on the toolbar. Can you provide us the extensions that you have installed on chrome ? We want to exclude the assumption where another extension can resize our window.

Best regards

**Comment by mrrobdlon** [comment]
Hi @scadra 

These are the extensions that I have installed

I don't think any of these are active when it happens - e.g. Dark Reader is off and there are no StyleBot styles for the pages where this happens.

Miljo only affects Salesforce web pages but this problem happens on various sites but is most common on Salesforce logins. I'm disabling Miljo to see if it makes a difference

![image](https://github.com/passbolt/passbolt_browser_extension/assets/940392/1a578f78-6a8d-442b-a5ad-05fbef5af92a)

**Comment by mrrobdlon** [comment]
I have just had the problem happen on https://www.webassessor.com/

I disabled all Chrome extensions except for Passbolt and the issue still occurred

![image](https://github.com/passbolt/passbolt_browser_extension/assets/940392/0cd77347-25e9-473b-856a-fea1e40b076a)

I wondered if it could it be that I have 2 monitors at different resolutions?

1) 2560 x 1440 scale: 100%
2) 3840 x 2160 scale: 150%

I tried opening the same webpage on my left monitor, number 1 and the behaviour was similar, but instead of the popup sliding to the left, it kept it's position and "grew" / stretched, to the right

![image](https://github.com/passbolt/passbolt_browser_extension/assets/940392/15602608-65f5-4a45-b217-35164bbe69b8)
